# Site settings
name: Cherie Lampley
markdown: kramdown
email: cherie@cherielampley.com
description: Cherie Lampley is a web strategy consultant, a writer, and a book reviewer

#blog commments
comments: true
permalink: /blog/:year/:month/:day/:title

# Build settings

